In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Introduction to TensorFlow

## Hello World in TensorFlow

* Import the TensorFlow library
```python
import tensorflow as tf
```

* Create a session with TensorFlow's run time
```python
with tf.Session('') as sess:
```

* Create some operations
```python
  c = tf.constant('Hello, world!')
```

* Run the operations
```python
print(sess.run(c))
```

In [3]:
import tensorflow as tf
with tf.Session('') as sess:
  c = tf.constant('Hello, world!')
  print(sess.run(c))

Hello, world!


### InteractiveSession
* `with tf.Session(''):` is cumbersome in a REPL, for instance.
* Use `tf.InteractiveSession()`
```python
sess = tf.InteractiveSession()
```

In [3]:
sess = tf.InteractiveSession()

### Constants
```python
# float vector
a = tf.constant([1.0, 2.0, 3.0, 4.0])
# int32 vector
b = tf.constant([5, 6, 7, 8])
# int32 2x2 matrix
c = tf.constant([5, 6, 7, 8], shape=[2, 2])
# int32 2x2 matrix
d = tf.constant([[5, 6], [7, 8]])
# int32 2x2x1 matrix
e = tf.constant([[[5], [6]], [[7], [8]]])
```
### Types
* Integer types
  - tf.int32, tf.int64, ...
* Floating point types
  - tf.float32, tf.float64, tf.complex64, ..
* Other
  - tf.bool, tf.string

### Constants from numpy arrays

In [4]:
c = tf.constant(random.rand(2, 2, 2))
print(sess.run(c))

[[[ 0.16995719  0.00398841]
  [ 0.57606181  0.65160659]]

 [[ 0.25170991  0.69922021]
  [ 0.02542203  0.55240549]]]


### Expressions

In [5]:
x = tf.constant([[5, 6], [7, 8]])
z = tf.matmul(x, x) + tf.matmul(x, [[1, 0], [0, 1]])
# eval() method on expressions is a shorthand for sess.run
print(z.eval())  # sess.run(z)

[[ 72  84]
 [ 98 114]]


![Graph](data/expression.png)

### Variables
* Primary mechanism for "State" in TensorFlow

In [13]:
# Create a variable with some initial value
v = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [7]:
# Get an operation that when run, initializes all variables
# declared so far
init = tf.initialize_all_variables()

In [12]:
# Initialize the variables
init.run()
# Inspect the variables
print(v.eval())

[[ 1.  2.]]


In [14]:
# Assign a new value to the variable
assign_v = v.assign(random.rand(2, 2))

In [15]:
# Perform the assignment and inspect the new value
sess.run(assign_v)
print(v.eval())

[[ 0.25413761  0.14187019]
 [ 0.58239782  0.24519511]]
