In [1]:
%pylab inline

/Users/keveman/nb/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


Populating the interactive namespace from numpy and matplotlib


## Introduction to TensorFlow

## Hello World in TensorFlow

* Import the TensorFlow library
```python
import tensorflow as tf
```

* Create a session with TensorFlow's run time
```python
with tf.Session('') as sess:
```

* Create some operations
```python
  c = tf.constant('Hello, world!')
```

* Run the operations
```python
print(sess.run(c))
```

In [2]:
import tensorflow as tf
with tf.Session('') as sess:
  c = tf.constant('Hello, world!')
  print(sess.run(c))

Hello, world!


### InteractiveSession
* `with tf.Session(''):` is cumbersome in a REPL, for instance.
* Use `tf.InteractiveSession()`
```python
sess = tf.InteractiveSession()
```

In [3]:
sess = tf.InteractiveSession()

### Constants
```python
# float vector
a = tf.constant([1.0, 2.0, 3.0, 4.0])
# int32 vector
b = tf.constant([5, 6, 7, 8])
# int32 2x2 matrix
c = tf.constant([5, 6, 7, 8], shape=[2, 2])
# int32 2x2 matrix
d = tf.constant([[5, 6], [7, 8]])
# int32 2x2x1 matrix
e = tf.constant([[[5], [6]], [[7], [8]]])
```
### Types
* Integer types
  - tf.int32, tf.int64, ...
* Floating point types
  - tf.float32, tf.float64, tf.complex64, ..
* Other
  - tf.bool, tf.string

### Constants from numpy arrays

In [4]:
c = tf.constant(random.rand(2, 2, 2))
print(sess.run(c))

[[[ 0.4464976   0.47595199]
  [ 0.16619108  0.20892644]]

 [[ 0.29731024  0.54044363]
  [ 0.22036439  0.08364951]]]


### Expressions

In [5]:
x = tf.constant([[5, 6], [7, 8]])
z = tf.matmul(x, x) + tf.matmul(x, [[1, 0], [0, 1]])
# eval() method on expressions is a shorthand for sess.run
print(z.eval())  # sess.run(z)

[[ 72  84]
 [ 98 114]]


![Graph](data/expression.png)

### Variables
* Primary mechanism for "State" in TensorFlow

In [6]:
# Create a variable with some initial value
v = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [7]:
# Get an operation that when run, initializes all variables
# declared so far
init = tf.initialize_all_variables()

In [8]:
# Initialize the variables
init.run()
# Inspect the variables
print(v.eval())

[[ 1.  2.]
 [ 3.  4.]]


In [9]:
# Assign a new value to the variable
assign_v = v.assign(random.rand(2, 2))

In [10]:
# Perform the assignment and inspect the new value
sess.run(assign_v)
print(v.eval())

[[ 0.61171943  0.83933121]
 [ 0.70918083  0.3796097 ]]


* Rest of TensorFlow built as libraries on top of these primitives
* `tf.nn` library
  - Neural network related functions - `softmax`, `relu`, `conv2d`
* `tf.image` library
  - Image processing functions - `crop`, `adjust_brightness`
* `tf.train` - Neural net training related functions
  - `GradientDescentOptimizer`, `exponential_decay`